# Generated by Django 5.2.17 on 2026-09-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyMedicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low Attention'), ('MEDIUM', 'Moderate Concern'), ('HIGH', 'High Urgency'), ('CRITICAL', 'Critical Emergency')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Alert'), ('UNDER_CARE', 'Under Medical Care'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('hospital_admitted', models.BooleanField(default=False)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('doctor_contact', models.CharField(blank=True, max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_health_alerts', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='students.student')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(default='O+', max_length=10)),
                ('allergies', models.TextField(blank=True, default='None known')),
                ('chronic_conditions', models.TextField(blank=True, default='None')),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('emergency_medical_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='schools.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor_name', models.CharField(max_length=150)),
                ('findings', models.TextField()),
                ('prescriptions', models.TextField(blank=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkups', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkups', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(default='1st Dose', max_length=50)),
                ('administered_date', models.DateField()),
                ('administered_by', models.CharField(blank=True, max_length=150)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='students.student')),
            ],
            options={
                'ordering': ['-administered_date'],
            },
        ),
    ]
