# Generated by Django 5.2.17 on 2026-09-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('low_stock_threshold', models.FloatField(default=25.0)),
                ('last_replenished', models.DateField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_stocks', to='schools.school')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('block_type', models.CharField(choices=[('BOYS', 'Boys Hostel Block'), ('GIRLS', 'Girls Hostel Block')], default='BOYS', max_length=20)),
                ('total_capacity', models.IntegerField(default=100)),
                ('school', models.ForeignKey(help_text='Strict school data isolation foreign key', on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='schools.school')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('DISCIPLINARY', 'Disciplinary Concern'), ('HEALTH', 'Health / Sickness in Dorm'), ('MAINTENANCE', 'Facility / Water / Light Issue'), ('SECURITY', 'Hostel Security / Boundary Concern'), ('OTHER', 'Other Incident')], default='DISCIPLINARY', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_incidents', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('escort_name', models.CharField(blank=True, max_length=150)),
                ('escort_contact', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (On Leave)'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to Hostel')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=6)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'ordering': ['floor', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast (सकाळचा नाश्ता)'), ('LUNCH', 'Lunch (दुपारचे जेवण)'), ('SNACK', 'Evening Snack (संध्याकाळचा नाश्ता)'), ('DINNER', 'Dinner (रात्रीचे जेवण)')], max_length=20)),
                ('menu_description', models.TextField(help_text='Items served: e.g., Dal, Rice, Chapati, Matki Usal, Milk')),
                ('students_served', models.IntegerField(default=0)),
                ('quality_status', models.CharField(default='Good / Inspected', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to='schools.school')),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('school', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('allocated_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_bed', to='students.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room')),
            ],
            options={
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
