# Generated by Django 5.2.17 on 2026-09-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BEDDING', 'Hostel Bedding & Cots'), ('UNIFORM', 'School Uniforms & Shoes'), ('BOOK', 'Library Books & Textbooks'), ('SPORTS', 'Sports & Physical Ed Equipment'), ('LAB', 'Science & ICT Lab Resources'), ('COMPUTER', 'Computers & Digital Tools'), ('HOSTEL_SUPPLY', 'Hostel & Sanitation Supplies'), ('GENERAL', 'General Institutional Assets')], default='GENERAL', max_length=30)),
                ('total_quantity', models.IntegerField(default=0)),
                ('allocated_quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='Units', max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('storage_location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(help_text='Strict school data isolation foreign key', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='schools.school')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock Added / Procured'), ('ISSUE', 'Issued to Student / Staff'), ('RETURN', 'Returned to Inventory'), ('DAMAGED', 'Marked Damaged / Written-off')], default='STOCK_IN', max_length=20)),
                ('quantity', models.IntegerField()),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_role', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='schools.school')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
