# Generated by Django 5.2.17 on 2026-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(db_index=True, help_text='Unique institutional school identifier (e.g. ASH001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('school_type', models.CharField(choices=[('GOVT_ASHRAM', 'Government Ashram School'), ('EMRS', 'Eklavya Model Residential School'), ('TRIBAL_RESIDENTIAL', 'Tribal Residential School'), ('AIDED_ASHRAM', 'Aided Ashram School')], default='GOVT_ASHRAM', max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school_id'], name='schools_sch_school__0feba0_idx')],
            },
        ),
    ]
