# Generated by Django 5.2.17 on 2026-09-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=200)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Application Pending'), ('SUBMITTED', 'Submitted to Dept'), ('UNDER_REVIEW', 'Under Review / Scrutiny'), ('APPROVED', 'Approved by Tribal Dept'), ('REJECTED', 'Rejected'), ('DISTRIBUTED', 'Amount Disbursed / Distributed')], default='PENDING', max_length=30)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(help_text='Strict school data isolation foreign key', on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UNIFORM', 'School Uniforms Distribution'), ('TEXTBOOKS', 'Government Free Textbooks'), ('STATIONERY', 'Notebooks & Educational Kit'), ('HOSTEL_KIT', 'Hostel Bedding & Personal Care Kit'), ('FOOD_BENEFIT', 'Direct Nutritional Support Scheme'), ('OTHER', 'General Tribal Welfare Scheme')], default='UNIFORM', max_length=30)),
                ('target_class', models.CharField(default='All Ashram Students', max_length=100)),
                ('total_eligible', models.IntegerField(default=0)),
                ('total_distributed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'Distribution in Progress'), ('COMPLETED', 'Fully Distributed')], default='IN_PROGRESS', max_length=30)),
                ('distribution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_schemes', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
